import { useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Download, Eye, Trash2, Plus } from 'lucide-react'
import { format } from 'date-fns'
import { payrollApi } from '../../services/api'
import { PageHeader, Button, Card, Table, Th, Td, Tr, Skeleton, Modal, EmptyState } from '../../components/ui'
import PfSheetModal, { saveBlob } from '../../components/PfSheetModal'

const CURR_YEAR = new Date().getFullYear()

export default function PfSheetsPage() {
  const qc = useQueryClient()
  const [year, setYear] = useState(String(CURR_YEAR))
  const [newOpen, setNewOpen] = useState(false)
  const [pickCycle, setPickCycle] = useState('')
  const [cycleId, setCycleId] = useState('')
  const [viewId, setViewId] = useState('')

  const { data: list, isLoading } = useQuery({
    queryKey: ['pf-sheets', year],
    queryFn: () => payrollApi.pfSheets(year).then(r => r.data.data as any[]),
  })

  const { data: cycles } = useQuery({
    queryKey: ['payroll-cycles'],
    queryFn: () => payrollApi.cycles().then(r => r.data.data as any[]),
    enabled: newOpen,
  })

  const { data: detail } = useQuery({
    queryKey: ['pf-sheet', viewId],
    queryFn: () => payrollApi.pfSheet(viewId).then(r => r.data.data),
    enabled: !!viewId,
  })

  async function download(row: any) {
    const res = await payrollApi.pfSheetDownload(row.id)
    saveBlob(res.data, row.fileName)
  }

  async function remove(row: any) {
    if (!window.confirm(`Delete PF sheet for ${row.payrollMonth}?`)) return
    await payrollApi.pfSheetDelete(row.id)
    qc.invalidateQueries({ queryKey: ['pf-sheets'] })
  }

  const eligible = (cycles || []).filter(c => c.status !== 'DRAFT')
  const yearOpts = [CURR_YEAR - 2, CURR_YEAR - 1, CURR_YEAR, CURR_YEAR + 1]

  return (
    <div className="space-y-5">
      <PageHeader
        title="PF Sheets"
        subtitle="History of PF sheets generated from payroll cycles"
        actions={
          <div className="flex gap-2">
            <select className="input" value={year} onChange={e => setYear(e.target.value)}>
              {yearOpts.map(y => <option key={y} value={y}>{y}</option>)}
            </select>
            <Button icon={<Plus size={14} />} onClick={() => { setPickCycle(''); setNewOpen(true) }}>New PF Sheet</Button>
          </div>
        }
      />

      <Card>
        {isLoading ? (
          <Skeleton className="h-48 rounded-xl" />
        ) : !list || list.length === 0 ? (
          <EmptyState title="No PF sheets yet" description="Generate one from a payroll cycle." />
        ) : (
          <Table>
            <thead>
              <tr className="border-b border-slate-100">
                <Th>Month</Th>
                <Th className="text-right">Employees</Th>
                <Th>Generated by</Th>
                <Th>Generated at</Th>
                <Th>Note</Th>
                <Th>Actions</Th>
              </tr>
            </thead>
            <tbody>
              {list.map(r => (
                <Tr key={r.id}>
                  <Td className="font-medium text-slate-800">{r.payrollMonth}</Td>
                  <Td className="text-right">
                    {r.employeeCount}
                    <span className="text-xs text-slate-400 ml-1">({r.paidCount} paid{r.extraCount > 0 ? ` + ${r.extraCount} added` : ''})</span>
                  </Td>
                  <Td>{r.generatedByName}</Td>
                  <Td>{format(new Date(r.createdAt), 'dd MMM yyyy, hh:mm a')}</Td>
                  <Td className="text-slate-500">{r.note || '—'}</Td>
                  <Td>
                    <div className="flex gap-1">
                      <Button size="sm" variant="ghost" icon={<Download size={13} />} onClick={() => download(r)}>Download</Button>
                      <Button size="sm" variant="ghost" icon={<Eye size={13} />} onClick={() => setViewId(r.id)}>View</Button>
                      <Button size="sm" variant="ghost" icon={<Trash2 size={13} />} onClick={() => remove(r)} />
                    </div>
                  </Td>
                </Tr>
              ))}
            </tbody>
          </Table>
        )}
      </Card>

      {/* Pick cycle */}
      <Modal
        open={newOpen}
        onClose={() => setNewOpen(false)}
        title="New PF Sheet"
        size="sm"
        footer={
          <>
            <Button variant="ghost" onClick={() => setNewOpen(false)}>Cancel</Button>
            <Button disabled={!pickCycle} onClick={() => { setCycleId(pickCycle); setNewOpen(false) }}>Next</Button>
          </>
        }
      >
        <label className="label">Payroll cycle</label>
        <select className="input" value={pickCycle} onChange={e => setPickCycle(e.target.value)}>
          <option value="">Select cycle</option>
          {eligible.map(c => <option key={c.id} value={c.id}>{c.payrollMonth} — {c.status}</option>)}
        </select>
      </Modal>

      <PfSheetModal cycleId={cycleId} open={!!cycleId} onClose={() => setCycleId('')} />

      {/* View list */}
      <Modal
        open={!!viewId}
        onClose={() => setViewId('')}
        title={detail ? `PF Sheet — ${detail.payrollMonth}` : 'PF Sheet'}
        size="md"
        footer={<Button variant="ghost" onClick={() => setViewId('')}>Close</Button>}
      >
        {!detail ? <Skeleton className="h-32 rounded-xl" /> : (
          <div className="divide-y divide-slate-50">
            {detail.employees.map((e: any) => (
              <div key={e.id} className="flex items-center justify-between py-2 text-sm">
                <span className="text-slate-800">{e.name} <span className="text-xs text-slate-400 ml-1">{e.employeeCode}</span></span>
                {e.isExtra && <span className="text-xs text-amber-600">Added</span>}
              </div>
            ))}
          </div>
        )}
      </Modal>
    </div>
  )
}
