import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Download, FileText } from 'lucide-react'
import { payslipApi, employeeApi } from '../../services/api'
import { useAuthStore } from '../../store/authStore'
import { PageHeader, Card, Table, Th, Td, Tr, EmptyState, Skeleton, StatusBadge, Rupee } from '../../components/ui'
import { format } from 'date-fns'

export default function MyPayslipsPage() {
  const { user } = useAuthStore()
  const [year, setYear] = useState(new Date().getFullYear())

  const { data: payslips, isLoading: loadingPayslips } = useQuery({
    queryKey: ['my-payslips', user?.id],
    queryFn: () => payslipApi.forEmployee(user!.id).then(r => r.data.data),
    enabled: !!user?.id,
  })

  const { data: history } = useQuery({
    queryKey: ['my-payroll-history', user?.id],
    queryFn: () => employeeApi.payrollHistory(user!.id).then(r => r.data.data),
    enabled: !!user?.id,
  })

  // Merge payslips with payroll entry data
  const entryMap = new Map((history || []).map((e: any) => [e.id, e]))
  const filtered = (payslips || []).filter((ps: any) => {
    if (!ps.cycle?.payrollMonth) return true
    return ps.cycle.payrollMonth.startsWith(String(year))
  })

  const years = [...new Set((payslips || []).map((ps: any) => ps.cycle?.payrollMonth?.slice(0, 4)).filter(Boolean))]
    .sort((a: any, b: any) => b - a)

  return (
    <div className="space-y-5">
      <PageHeader title="My Payslips" subtitle="Download your payslips for any month" />

      {/* Year filter */}
      <div className="flex gap-2">
        {years.map((y: any) => (
          <button key={y} onClick={() => setYear(Number(y))}
            className={`px-4 py-1.5 rounded-lg text-sm font-medium transition-colors ${
              year === Number(y) ? 'bg-brand-600 text-white' : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-50'
            }`}>
            {y}
          </button>
        ))}
      </div>

      <Card>
        {loadingPayslips ? <Skeleton className="h-64 m-4" /> : !filtered.length ? (
          <EmptyState icon={<FileText size={22} />} title="No payslips found"
            description="Payslips appear here once generated by HR after each payroll cycle." />
        ) : (
          <Table>
            <thead>
              <tr className="border-b border-slate-100">
                <Th>Month</Th><Th className="text-right">Gross</Th><Th className="text-right">Deductions</Th>
                <Th className="text-right">Net Salary</Th><Th>Status</Th><Th>Download</Th>
              </tr>
            </thead>
            <tbody>
              {filtered.map((ps: any) => {
                const entry = entryMap.get(ps.entryId) as any
                const deductions = entry
                  ? ['pfAmount','esiAmount','ptAmount','tdsAmount','lopAmount','loanDeduction'].reduce((s: number, k: string) => s + Number(entry[k] || 0), 0)
                  : 0
                return (
                  <Tr key={ps.id}>
                    <Td>
                      <p className="font-semibold text-slate-800">{ps.cycle?.payrollMonth}</p>
                      {ps.generatedAt && <p className="text-xs text-slate-400">Generated {format(new Date(ps.generatedAt), 'dd MMM yyyy')}</p>}
                    </Td>
                    <Td className="text-right">{entry ? <Rupee amount={entry.grossSalary} /> : '—'}</Td>
                    <Td className="text-right">{deductions > 0 ? <Rupee amount={deductions} className="text-red-500" /> : '—'}</Td>
                    <Td className="text-right font-bold">{entry ? <Rupee amount={entry.netSalary} /> : '—'}</Td>
                    <Td><StatusBadge status={ps.status} /></Td>
                    <Td>
                      {ps.pdfUrl
                        ? <a href={ps.pdfUrl} target="_blank" rel="noreferrer"
                            className="inline-flex items-center gap-1.5 text-xs font-semibold text-brand-600 hover:text-brand-800 bg-brand-50 hover:bg-brand-100 px-3 py-1.5 rounded-lg transition-colors">
                            <Download size={12} /> Download PDF
                          </a>
                        : <span className="text-xs text-slate-300">Not ready</span>
                      }
                    </Td>
                  </Tr>
                )
              })}
            </tbody>
          </Table>
        )}
      </Card>
    </div>
  )
}
